"""
Alert Database Model.

Represents security incident alerts generated by the fraud risk engine
with complete SOC lifecycle management and case correlation.
"""

from datetime import datetime, timezone
from typing import Dict, Any, Optional
from app.extensions import db


class Alert(db.Model):
    """Security alert record triggered by high-risk transactions with SOC lifecycle states."""

    __tablename__ = "alerts"
    __table_args__ = (
        db.CheckConstraint("severity IN ('LOW', 'MEDIUM', 'HIGH', 'CRITICAL')", name="check_alert_severity"),
        db.CheckConstraint(
            "status IN ('OPEN', 'ACKNOWLEDGED', 'INVESTIGATING', 'RESOLVED', 'FALSE_POSITIVE', 'ESCALATED', 'DISMISSED')",
            name="check_alert_status",
        ),
        db.Index("ix_alerts_status", "status"),
        db.Index("ix_alerts_user_id_status", "user_id", "status"),
        {"sqlite_autoincrement": True},
    )

    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    transaction_id = db.Column(
        db.Integer, db.ForeignKey("transactions.id", ondelete="CASCADE"), nullable=False, unique=True, index=True
    )
    user_id = db.Column(db.Integer, db.ForeignKey("users.id", ondelete="CASCADE"), nullable=False, index=True)
    case_id = db.Column(db.Integer, db.ForeignKey("soc_cases.id", ondelete="SET NULL"), nullable=True, index=True)

    alert_type = db.Column(db.String(50), default="FRAUD_ALERT", nullable=False)
    severity = db.Column(db.String(20), default="HIGH", nullable=False)  # 'LOW', 'MEDIUM', 'HIGH', 'CRITICAL'
    message = db.Column(db.Text, nullable=False)
    status = db.Column(db.String(20), default="OPEN", nullable=False)

    # SOC Assignment & Triage Lifecycle
    assigned_to_id = db.Column(db.Integer, db.ForeignKey("users.id", ondelete="SET NULL"), nullable=True, index=True)
    assigned_at = db.Column(db.DateTime, nullable=True)
    acknowledged_at = db.Column(db.DateTime, nullable=True)
    acknowledged_by = db.Column(db.String(100), nullable=True)

    # Resolution & Investigation
    notes = db.Column(db.Text, nullable=True)  # Investigation & resolution notes
    resolved_by = db.Column(db.String(100), nullable=True)  # Admin identifier
    resolved_at = db.Column(db.DateTime, nullable=True)

    # Deduplication & Correlation
    dedup_signature = db.Column(db.String(64), nullable=True, index=True)
    correlation_count = db.Column(db.Integer, default=1, nullable=False)

    created_at = db.Column(db.DateTime, default=lambda: datetime.now(timezone.utc), nullable=False, index=True)

    # Relationships
    transaction = db.relationship("Transaction", back_populates="alert")
    user = db.relationship("User", foreign_keys=[user_id], back_populates="alerts")
    assignee = db.relationship("User", foreign_keys=[assigned_to_id])
    case = db.relationship("SOCCase", back_populates="alerts")

    def to_dict(self) -> Dict[str, Any]:
        """Convert alert instance to JSON-serializable dictionary."""
        return {
            "id": self.id,
            "transaction_id": self.transaction_id,
            "user_id": self.user_id,
            "case_id": self.case_id,
            "alert_type": self.alert_type,
            "severity": self.severity,
            "message": self.message,
            "status": self.status,
            "assigned_to_id": self.assigned_to_id,
            "assigned_to_email": self.assignee.email if self.assignee else None,
            "assigned_at": self.assigned_at.isoformat() if self.assigned_at else None,
            "acknowledged_at": self.acknowledged_at.isoformat() if self.acknowledged_at else None,
            "acknowledged_by": self.acknowledged_by,
            "notes": self.notes,
            "resolved_by": self.resolved_by,
            "resolved_at": self.resolved_at.isoformat() if self.resolved_at else None,
            "dedup_signature": self.dedup_signature,
            "correlation_count": self.correlation_count,
            "created_at": self.created_at.isoformat() if self.created_at else None,
        }

    def __repr__(self) -> str:
        return f"<Alert {self.id}: Tx {self.transaction_id} [{self.severity}] - {self.status} Case:{self.case_id}>"
