"""
Alert Database Model.

Represents high-risk security alerts generated by the fraud risk engine
for administrative monitoring and security investigation.
"""

from datetime import datetime, timezone
from app.extensions import db


class Alert(db.Model):
    """Security alert record triggered by high-risk transactions."""

    __tablename__ = "alerts"
    __table_args__ = (
        db.CheckConstraint("severity IN ('MEDIUM', 'HIGH', 'CRITICAL')", name="check_alert_severity"),
        db.CheckConstraint("status IN ('OPEN', 'RESOLVED', 'DISMISSED')", name="check_alert_status"),
        db.Index("ix_alerts_status", "status"),
        {"sqlite_autoincrement": True},
    )

    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    transaction_id = db.Column(
        db.Integer, db.ForeignKey("transactions.id", ondelete="CASCADE"), nullable=False, unique=True, index=True
    )
    user_id = db.Column(db.Integer, db.ForeignKey("users.id", ondelete="CASCADE"), nullable=False, index=True)
    alert_type = db.Column(db.String(50), default="FRAUD_ALERT", nullable=False)
    severity = db.Column(db.String(20), default="HIGH", nullable=False)  # 'MEDIUM', 'HIGH', 'CRITICAL'
    message = db.Column(db.Text, nullable=False)
    status = db.Column(db.String(20), default="OPEN", nullable=False)  # 'OPEN', 'RESOLVED', 'DISMISSED'
    notes = db.Column(db.Text, nullable=True)  # Investigation & resolution notes
    resolved_by = db.Column(db.String(100), nullable=True)  # Admin who resolved/dismissed
    created_at = db.Column(db.DateTime, default=lambda: datetime.now(timezone.utc), nullable=False, index=True)
    resolved_at = db.Column(db.DateTime, nullable=True)

    # Relationships
    transaction = db.relationship("Transaction", back_populates="alert")
    user = db.relationship("User", back_populates="alerts")

    def to_dict(self) -> dict:
        """Convert alert instance to JSON-serializable dictionary."""
        return {
            "id": self.id,
            "transaction_id": self.transaction_id,
            "user_id": self.user_id,
            "alert_type": self.alert_type,
            "severity": self.severity,
            "message": self.message,
            "status": self.status,
            "notes": self.notes,
            "resolved_by": self.resolved_by,
            "created_at": self.created_at.isoformat() if self.created_at else None,
            "resolved_at": self.resolved_at.isoformat() if self.resolved_at else None,
        }

    def __repr__(self) -> str:
        return f"<Alert {self.id}: Tx {self.transaction_id} [{self.severity}] - {self.status}>"
